# Generated by Django 5.2.1 on 2025-07-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="borrowing.borrowing",
            ),
        ),
    ]
